apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: networking
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:25P38p5LEa1ehzwmeDEt4bqWcJcD8HtVdWGo4Qqs5+55P+U2dVNERg==,iv:c/RKd4yyViJbFRj4oK6FUS/Aj8CA9nA2oQFhMILD3dE=,tag:fAUlJn5G5S0TLQ34kyEyXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ws3x77ygr4a3eweh2v3zhxc0uw8eury0eql343jq45a3tmxsr9vq9730lt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTk5SNXZWdXRGNUtYQVBp
            VUN6ZnF0OFdabzFRM0U3KzJTbFZQVGFFL0dZCnowQ3dVS01NZlNXYkcyNnkrRGFY
            TU9ibHBKR2V6UUxLMG5EWGM4VldJRVEKLS0tIGc3L0NycDEra0NhU1paTFdpc3hM
            VVBvR1I4NGJwWFpadjAxOUZyTy8rNjQK6tidSEMvisXS9+ucwlpiA/9MC9ntHRxM
            4pSFrRSJOsgwtiOYNS7aGxAV8ypib8pQHhS/4Fjf+RULQwGAPrctRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T16:10:22Z"
    mac: ENC[AES256_GCM,data:i2IMZzA+OnJn4oq0lFphAW/TfRI9uu5yUZ00JR9fAZuPvheAmSoVs7V2kwcf0m+Lruowpx8FXVxtrmpc2Z9sCWhKGpox9SJ1r68AAhOELe9bNuJJOjJrKI2i64M7ycjMkaMerrZ4N94QaSYgD57SvHGVGtMZoHFitqC8qcX+0KI=,iv:q6BG/XWbSB/uVCGQTTQJkckOL7UcrLBTFGc8ydOmPT0=,tag:F7Lp+xwhsxAj9IejDUjOqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
