---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: v1.6.0
      ingressClass: nginx
      kind: DaemonSet
      ingressClassRessource:
        enabled: true
        name: nginx
        default: true
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
        forwarded-for-header: "CF-Connecting-IP"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi