---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: extranet
---
apiVersion: v1
kind: Namespace
metadata:
  name: intranet
  labels:
    routed-gateway: "true"