apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../all/namespaces.yaml
- ../all/cert-manager
- ../all/external-dns

patchesStrategicMerge:
- cert-manager/wildcard-certificate.yaml